[package]
name = "nova-wasm"
version = "0.1.0"
edition = "2021"
authors = ["iKi <180210171+nff747@users.noreply.github.com>"]
description = "A custom statically typed systems language compiling directly to WebAssembly binary format without LLVM"
license = "Apache-2.0"

[lib]
name = "nova_wasm"
path = "src/lib.rs"

[[bin]]
name = "novac"
path = "src/main.rs"

[dependencies]

[dev-dependencies]
